services:
  - type: web
    name: rentalbackend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: >
      python -c "import os; import django; os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'RentalService.settings'); 
      django.setup(); from django.core.management import call_command; 
      call_command('migrate'); 
      try: call_command('loaddata', 'data.json'); print('Данные успешно загружены!'); 
      except Exception as e: print(f'Ошибка при загрузке данных: {e}');" && 
      gunicorn RentalService.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,rentsewxrr.netlify.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://rentsewxrr.netlify.app,http://localhost:3000"
      - key: PYTHON_VERSION
        value: 3.11.0 