# Generated by Django 5.1.6 on 2025-02-28 18:05

import rentApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', rentApp.models.CustomUserManager()),
            ],
        ),
    ]
