# Generated by Django 5.1.6 on 2025-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='rental_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за день'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
