# Generated by Django 5.1.6 on 2025-03-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0005_remove_userprofile_completed_rentals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='driver_license',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Водительское удостоверение'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
