# Generated by Django 5.1.6 on 2025-03-02 20:15

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0006_userprofile_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='rental_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='damage_fee',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='late_fee',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='return_date',
        ),
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='personal_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 20, 15, 6, 227614, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
