# Generated by Django 5.1.6 on 2025-03-05 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0007_alter_rental_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_approved_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждена'), ('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('client', 'Клиент'), ('operator', 'Оператор'), ('technician', 'Технический специалист'), ('accountant', 'Бухгалтер'), ('manager', 'Руководитель')], max_length=20, unique=True),
        ),
    ]
