# Generated by Django 5.1.6 on 2025-03-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0009_remove_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждена'), ('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('rejected', 'Отклонена')], default='pending', max_length=20),
        ),
    ]
