# Generated by Django 5.1.6 on 2025-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0011_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(max_length=100, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('in_rent', 'В аренде'), ('maintenance', 'На обслуживании'), ('pending', 'Ожидает подтверждения')], default='available', max_length=20, verbose_name='Статус'),
        ),
    ]
