# Generated by Django 5.1.6 on 2025-03-05 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0012_remove_car_is_available_alter_car_condition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name': 'Штраф', 'verbose_name_plural': 'Штрафы'},
        ),
        migrations.AddField(
            model_name='penalty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penalty',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penalty',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='rentApp.rental'),
        ),
    ]
