# Generated by Django 5.1.6 on 2025-03-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0013_alter_penalty_options_penalty_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='applied_discount',
            field=models.IntegerField(default=0),
        ),
    ]
