# Generated by Django 5.1.6 on 2025-03-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0017_user_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
