# Generated by Django 5.1.6 on 2025-03-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0018_alter_role_options_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('satisfactory', 'Удовлетворительное'), ('needs_repair', 'Требует ремонта')], default='excellent', max_length=20, verbose_name='Состояние'),
        ),
    ]
